### ISSUE TITLE
Add support for payment method updates

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-restrict-content-pro#22]
From customer:

> We use Restrict Content Pro with Pronamic for the subscriptions. If the user's card expires, we lose the user.
> 
> Can we use the `rcp_update_card` shortcode for payment method updates
> - https://restrictcontentpro.com/knowledgebase/rcp_update_card/
> 
> Or is that unsupported with Pronamic and should we use a different way?

We can hook into `rcp_membership_can_update_billing_card` and use the subscription mandate selection URL as action URL on the RCP account page. The `rcp_update_card` shortcode can only be used to display a form like this:

![file-hJ90kgI3KT](https://github.com/user-attachments/assets/fca0ff6d-b852-4858-90f1-965c54128171)

**Comment by remcotolsma** [comment]
I don't know if the changes in https://github.com/pronamic/wp-pronamic-pay-restrict-content-pro/pull/23 are the right way forward. Perhaps we should keep it simpler by using `rcp_update_billing_card` to create a Mollie creditcard mandate? Because this Restrict Content Pro functionality seems to focus on credit cards:

- https://github.com/search?q=rcp_card_number&type=code
- https://github.com/search?q=rcp_update_billing_card&type=code

Also using this Restrict Content Pro functionality for SEPA direct debit mandates seems less future-proof to me.

And otherwise we would be better off using the `rcp_subscription_details_actions` filter separately from the `rcp_membership_can_update_billing_card` filter to add our action mandate change action URL?

**Comment by rvdsteege** [comment]
> And otherwise we would be better off using the `rcp_subscription_details_actions` filter separately from the `rcp_membership_can_update_billing_card` filter to add our action mandate change action URL?

Did some changes in https://github.com/pronamic/wp-pronamic-pay-restrict-content-pro/pull/23 for this.
